### ISSUE TITLE
UberJAR is broken

### ISSUE THREAD

**Issue by ottlinger** [ottlinger/fotocollector#7]
Guava seems to be missing:

```
$ java -jar build/libs/fotocollector-0.0.2-SNAPSHOT.jar 
Will work on directory: workspace/fotocollector
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Sets
        at de.aikiit.fotocollector.ScanResult.<init>(ScanResult.java:20)
        at de.aikiit.fotocollector.main.PictureScanner.getFiles(PictureScanner.java:63)
        at de.aikiit.fotocollector.FotoCollectorApplication.main(FotoCollectorApplication.java:26)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Sets
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more

```

**Comment by ottlinger** [comment]
Maybe handcrafted way of building the fatJar is bad - try out stuff from Junit project:

* https://github.com/junit-team/junit5/issues/258#issuecomment-219000343
* https://github.com/junit-team/junit5/issues/146
* https://github.com/aalmiray/junit5/blob/c4320bd6f2f34d77f2fa4ef1e95b3bb4eda5bc96/junit-console/build.gradle
* https://github.com/johnrengelman/shadow

**Comment by ottlinger** [comment]
https://github.com/johnrengelman/shadow
seems to be a more Gradle5-compatible way to go ahead.

**Comment by ottlinger** [comment]
21:42 $ java -jar build/libs/fotocollector-0.0.2-SNAPSHOT-all.jar
___________     __         _________        .__  .__                 __
\_   _____/____/  |_  ____ \_   ___ \  ____ |  | |  |   ____   _____/  |_  ___________
 |    __)/  _ \   __\/  _ \/    \  \/ /  _ \|  | |  | _/ __ \_/ ___\   __\/  _ \_  __ \
 |     \(  <_> )  | (  <_> )     \___(  <_> )  |_|  |_\  ___/\  \___|  | (  <_> )  | \/
 \___  / \____/|__|  \____/ \______  /\____/|____/____/\___  >\___  >__|  \____/|__|
     \/                            \/                      \/     \/
Starting collection on directory: /Users/foo/fotocollector
No results found. Nothing to be done :-)
21:42 $

**Comment by ottlinger** [comment]
Works like a charm with Gradle5.
